# Datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

# Swagger
quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

# Docker Image
quarkus.container-image.build=true
quarkus.container-image.push=true

# Application Variables
#comma-separated list service UUID of values
#recovery.failed-service-uuids=5c58f5e5-4ebb-4a0a-bf89-c62c470213b9

# Testing
%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.image-name=mysql:8.0