# Datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

# Swagger
quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

# Docker Image
quarkus.container-image.build=true
quarkus.container-image.push=true

# Testing
%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.image-name=mysql:8.0

#Kafka
%prod.mp.messaging.outgoing.balancing-recommendation.connector=smallrye-kafka
%test.mp.messaging.outgoing.balancing-recommendation.connector=smallrye-in-memory
mp.messaging.outgoing.balancing-recommendation.topic=balancing-recommendation
mp.messaging.outgoing.balancing-recommendation.value.serializer=org.apache.kafka.common.serialization.StringSerializer