@startuml Asset Management Business Process
title Asset Management Business Process

participant "Camunda" as C
participant "Kong" as K
participant "Asset Microservice" as P

C -> K : CRUD Request
K -> P : Forward Request
note right of P
  Process request
end note
P -> K : Response
K -> C : Forward Response

@enduml
