@startuml Prosumer Management Business Process
title Prosumer Management Business Process

participant "Camunda" as C
participant "Kong" as K
participant "Prosumer Microservice" as P

C -> K : CRUD Request
K -> P : Forward CRUD Request
note right of P
  Process request
end note
P -> K : Response
K -> C : Forward Response

@enduml
