@startuml UtilityOperatorManagement
title Utility Operator Management Business Process

participant Camunda
participant Kong
participant "Utility Operator Microservice" as MS

Camunda -> Kong : CRUD Request
Kong -> MS : Forward CRUD Request
note right of MS : Process request
MS -> Kong : Response
Kong -> Camunda : Forward Response
@enduml