@startuml AssetLinkDeletion
title Asset Link Deletion Business Process

/'
Stop the consumption of the topic(s) by the Telemetry Microservice POST /Telemetry/stop
Delete the topic(s) from Kafka using the AssetLink microservice DELETE /AssetLink/topic/{prosumerId}/{utilityOperatorId}
Delete the asset link. DELETE /AssetLink/{id}
'/

participant Camunda
participant Kong
participant "AssetLink Microservice" as Link
participant "Telemetry Microservice" as Tel
participant Kafka

Camunda -> Kong : Stop Consuming Request
Kong -> Tel : Forward Request
note right of Tel : Stop Consumer Thread
Tel -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Delete Topic Request
Kong -> Kafka : Forward Request
note right of Kafka : Delete Topic
Kafka -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Delete Request
Kong -> Link : Forward Request
note right of Link : Process request
Link -> Kong : Response
Kong -> Camunda : Forward Response
@enduml
