@startuml AssetLinkDeletion
title Asset Link Deletion Business Process

/'
Stop the consumption of the topic(s) by the Telemetry Microservice POST /Telemetry/stop
Delete the topic(s) from Kafka using the AssetLink microservice DELETE /AssetLink/topic/{assetId}/{gridCellId}
Remove the grid cell to the asset(s) using the Asset MicroService PUT /Asset/{id}
Delete the asset link we need to first make a contract between the prosumer and utility operator. POST /AssetLink
'/

participant Camunda
participant Kong
participant "AssetLink Microservice" as Link
participant "Asset Microservice" as Asset
participant "Telemetry Microservice" as Tel
participant Kafka

Camunda -> Kong : Stop Consuming Request
Kong -> Tel : Forward Request
note right of Tel : Stop Consumer Thread
Tel -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Delete Topic Request
Kong -> Kafka : Forward Request
note right of Kafka : Delete Topic
Kafka -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Clear Asset's Grid Cell Id Request
Kong -> Asset : Forward Request
note right of Asset : Process request
Asset -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Delete Request
Kong -> Link : Forward Request
note right of Link : Process request
Link -> Kong : Response
Kong -> Camunda : Forward Response
@enduml