@startuml FlexibilityEmission
title Flexibility Emission Business Process

participant Camunda
participant Kong
participant "Prosumer Microservice" as Pros
participant "Asset Microservice" as Asset
participant "Telemetry Microservice" as Tel
participant "Grid Cell" as GC
participant "Flexibility Emission Microservice" as Flex
participant Kafka

Camunda -> Kong : Read Request
Kong -> Pros : Forward Read Request
note right of Pros : Process request
Pros -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Read Prosumer Assets Request
Kong -> Asset : Forward Read Request
note right of Asset : Process request
Asset -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Read Assets' Latest Telemetry Event Request
Kong -> Tel : Forward Read Request
note right of Tel : Process request
Tel -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Read by Id Request
Kong -> GC : Forward Read Request
note right of GC : Process request
GC -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Evaluate Request
Kong -> Flex : Forward Evaluate Request
note right of Flex : Process request
Flex -> Kafka : Produce to Topic: flexibility-offers
Flex -> Kong : Response
Kong -> Camunda : Forward Response
@enduml