@startuml GridBalancingRecommendation
title Grid Balancing Recommendation Business Process

/'
Get all grid cells using the Grid Cell Microservice. GET /GridCell
Get active assets in those grid cells using the Asset Microservice. GET /Asset/active/by-grid-cell-ids?cellIds=<id>
Get latest telemetry events for those assets in current grid cells using the Telemetry Microservice. GET /Telemetry/latest
Send to Grid Balancing Microservice for processing and produce balancing events. POST /balance

The business process does not need to query the Prosumer, Utility Operator and Asset Link microservices - as it is is
the project statement - since all the information we need can be obtained from the previous endpoints.
'/

participant Camunda
participant Kong
participant "Grid Cell Microservice" as GC
participant "Asset Microservice" as Asset
participant "Telemetry Microservice" as Tel
participant "Grid Balancing Microservice" as GB
participant Kafka

Camunda -> Kong : Read All Grid Cells Request
Kong -> GC : Forward Request
note right of GC : Process request
GC -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Read Active Assets by Grid Cell Ids Request
Kong -> Asset : Forward Request
note right of Asset : Process request
Asset -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Read Latest Telemetry Events Request
Kong -> Tel : Forward Request
note right of Tel : Process request
Tel -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Analyse Request
Kong -> GB : Forward Request
note right of GB : Process request
GB -> Kafka : Produce to Topic: balancing-recommendation
GB -> Kong : Response
Kong -> Camunda : Forward Response
@enduml