@startuml GridBalancingRecommendation
title Grid Balancing Recommendation Business Process

participant VPaaS
participant Camunda as C
participant Kong
participant "Prosumer Microservice" as P
participant "Asset Link Microservice" as AL
participant "Utility Operator Microservice" as UO
participant "Grid Cell Microservice" as GC
participant "Telemetry Microservice" as T
participant "Grid Balancing Microservice" as GB
participant Kafka


C -> Kong : Read request
Kong -> P : Forward Request
P -> Kong : Response
Kong -> C : Forward Response

VPaaS -> C : Send Prosumer Id

C -> Kong : Read Prosumer Asset Links request
Kong -> AL : Forward Request
AL -> Kong : Response
Kong -> C : Forward Response

VPaaS -> C : Send Asset Link Id

C -> Kong : Read Asset Link Utility Operator request
Kong -> UO : Forward Request
UO -> Kong : Response
Kong -> C : Forward Response

C -> Kong : Read Utility Operator Grid Cells request
Kong -> GC : Forward Request
GC -> Kong : Response
Kong -> C : Forward Response

VPaaS -> C : Send Grid Cell Ids

C -> Kong : Read Grid Cell Ids Telemetry Events
Kong -> T : Forward Request
T -> Kong : Response
Kong -> C : Forward Response

C -> Kong : Balance Load Between Grid Cells
Kong -> GB : Forward Request
GB -> Kafka : Produce to balancing-recommendation
note right of Kafka: Event Produced
GB -> Kong : Response
Kong -> C : Forward Response

C -> VPaaS  : Review Balancing Recommendations

@enduml