@startuml TelemetryIngestion
title Telemetry Ingestion

participant "Telemetry Microservice" as Tel
participant Kafka

note right of Kafka : New Event
Tel -> Kafka   : Cosume Event
Tel <- Kafka
note right of Tel : Store Event
@enduml