@startuml EnergyAnalytics
title Energy Analytics Business Process

/'
Get all assets using the Asset Microservice. GET /Asset
Get last hour telemetry events using the Telemetry Microservice. GET /Telemetry/last-hour
Send to Energy Analytics Microservice for processing. POST /EnergyAnalytics/analyse

The business process does not need to query the Prosumer or Utility Operator (and even Grid Cell) microservices
- as it is in the project statement - since all the information we need can be obtained from the previous endpoints.
The asset_id to prosumer_id mapping is already carried by the asset records, and the grid_cell_id is already carried
by each telemetry event.
'/


participant Camunda
participant Kong
participant "Asset Microservice" as Asset
participant "Telemetry Microservice" as Tel
participant "Energy Analytics Microservice" as EA
participant Kafka

Camunda -> Kong : Read All Assets Request
Kong -> Asset : Forward Request
note right of Asset : Process request
Asset -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Read Last Hour Telemetry Events Request
Kong -> Tel : Forward Request
note right of Tel : Process request
Tel -> Kong : Response
Kong -> Camunda : Forward Response

Camunda -> Kong : Compute Request
Kong -> EA : Forward Request
note right of EA : Process request
EA -> Kafka : Produce to Topic: energy-discharged-by-zone
EA -> Kafka : Produce to Topic: generated-energy-by-prosumer
EA -> Kafka : Produce to Topic: consumed-energy-by-prosumer
EA -> Kafka : Produce to Topic: average-soc-by-zone
EA -> Kong : Response
Kong -> Camunda : Forward Response
@enduml