# Datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

# Swagger
quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

# Docker Image
quarkus.container-image.build=true
quarkus.container-image.push=true

# Testing
%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.image-name=mysql:8.0

# Kafka
%prod.mp.messaging.outgoing.energy-discharged-by-zone.connector=smallrye-kafka
%test.mp.messaging.outgoing.energy-discharged-by-zone.connector=smallrye-in-memory
mp.messaging.outgoing.energy-discharged-by-zone.topic=energy-discharged-by-zone
mp.messaging.outgoing.energy-discharged-by-zone.value.serializer=org.apache.kafka.common.serialization.StringSerializer

%prod.mp.messaging.outgoing.generated-energy-by-prosumer.connector=smallrye-kafka
%test.mp.messaging.outgoing.generated-energy-by-prosumer.connector=smallrye-in-memory
mp.messaging.outgoing.generated-energy-by-prosumer.topic=generated-energy-by-prosumer
mp.messaging.outgoing.generated-energy-by-prosumer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

%prod.mp.messaging.outgoing.consumed-energy-by-prosumer.connector=smallrye-kafka
%test.mp.messaging.outgoing.consumed-energy-by-prosumer.connector=smallrye-in-memory
mp.messaging.outgoing.consumed-energy-by-prosumer.topic=consumed-energy-by-prosumer
mp.messaging.outgoing.consumed-energy-by-prosumer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

%prod.mp.messaging.outgoing.average-soc.connector=smallrye-kafka
%test.mp.messaging.outgoing.average-soc.connector=smallrye-in-memory
mp.messaging.outgoing.average-soc.topic=average-soc
mp.messaging.outgoing.average-soc.value.serializer=org.apache.kafka.common.serialization.StringSerializer

quarkus.container-image.group=antoniomiguelpalma9999
