quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

quarkus.container-image.build=true
quarkus.container-image.push=true

#quarkus.docker.buildx.platform=linux/amd64


mp.messaging.outgoing.energy-discharged-by-zone.connector=smallrye-kafka
mp.messaging.outgoing.energy-discharged-by-zone.topic=energy-discharged-by-zone
mp.messaging.outgoing.energy-discharged-by-zone.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.generated-energy-by-prosumer.connector=smallrye-kafka
mp.messaging.outgoing.generated-energy-by-prosumer.topic=generated-energy-by-prosumer
mp.messaging.outgoing.generated-energy-by-prosumer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.consumed-energy-by-prosumer.connector=smallrye-kafka
mp.messaging.outgoing.consumed-energy-by-prosumer.topic=consumed-energy-by-prosumer
mp.messaging.outgoing.consumed-energy-by-prosumer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.average-soc.connector=smallrye-kafka
mp.messaging.outgoing.average-soc.topic=average-soc
kafka.bootstrap.servers=
quarkus.datasource.reactive.url=
quarkus.container-image.group=joaoruss0
