# Datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

# Swagger
quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

# Docker Image
quarkus.container-image.build=true
quarkus.container-image.push=true

# Kafka
%test.kafka.bootstrap.servers=localhost:9092

%prod.mp.messaging.outgoing.flexibility-offers.connector=smallrye-kafka
%test.mp.messaging.outgoing.flexibility-offers.connector=smallrye-in-memory
mp.messaging.outgoing.flexibility-offers.topic=flexibility-offers
mp.messaging.outgoing.flexibility-offers.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Testing
%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.image-name=mysql:8.0

quarkus.container-image.group=antoniomiguelpalma9999
