quarkus.datasource.db-kind=mysql
quarkus.datasource.username=teste
quarkus.datasource.password=testeteste

quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true

quarkus.container-image.build=true
quarkus.container-image.push=true

#quarkus.docker.buildx.platform=linux/amd64

quarkus.container-image.group=joaoruss0
quarkus.datasource.reactive.url=mysql://ieproject202620260507190750676500000001.chvkqwfiehtt.us-east-1.rds.amazonaws.com:3306/VPPaaS

#mp.messaging.outgoing.flexibility-offers.connector=smallrye-kafka
#mp.messaging.outgoing.flexibility-offers.topic=Flexibility-Offers
#mp.messaging.outgoing.flexibility-offers.value.serializer=org.apache.kafka.common.serialization.StringSerializer